export declare const SHEKEL_CURRENCY_SYMBOL = "\u20AA";
export declare const SHEKEL_CURRENCY_KEYWORD = "\u05E9\"\u05D7";
export declare const ALT_SHEKEL_CURRENCY = "NIS";
export declare const SHEKEL_CURRENCY = "ILS";
export declare const DOLLAR_CURRENCY_SYMBOL = "$";
export declare const DOLLAR_CURRENCY = "USD";
export declare const EURO_CURRENCY_SYMBOL = "\u20AC";
export declare const EURO_CURRENCY = "EUR";
export declare const ISO_DATE_FORMAT = "YYYY-MM-DD[T]HH:mm:ss.SSS[Z]";
export declare const ISO_DATE_REGEX: RegExp;
